const MOCK_PROPERTIES = [
    {
        id: "p1",
        title: "Cozy 2BR Apartment",
        price: 1200,
        address: "12 Main St",
        beds: 2,
        baths: 1,
        area: 750,
        images: [],
        description: "A cozy 2 bedroom apartment in the city center.",
    },
    {
        id: "p2",
        title: "Spacious House with Garden",
        price: 2500,
        address: "45 Oak Ave",
        beds: 4,
        baths: 3,
        area: 2200,
        images: [],
        description: "Large family house with a backyard and garage.",
    },
    {
        id: "p3",
        title: "Modern Loft Downtown",
        price: 1800,
        address: "9 Central Blvd",
        beds: 1,
        baths: 1,
        area: 620,
        images: [],
        description: "Sunny loft with open plan living and city views.",
    },
    {
        id: "p4",
        title: "Suburban Family Home",
        price: 2100,
        address: "78 Pine St",
        beds: 3,
        baths: 2,
        area: 1400,
        images: [],
        description: "Comfortable family home in a quiet neighborhood.",
    },
    {
        id: "p5",
        title: "Luxury Villa",
        price: 5200,
        address: "Ocean Drive 15",
        beds: 5,
        baths: 4,
        area: 4800,
        images: [],
        description: "High-end villa with pool and sea view.",
    },
    {
        id: "p6",
        title: "Compact Studio",
        price: 900,
        address: "101 Market St",
        beds: 0,
        baths: 1,
        area: 320,
        images: [],
        description: "Affordable studio perfect for students or singles.",
    },
    {
        id: "p7",
        title: "Townhouse Near Park",
        price: 1950,
        address: "22 Park Lane",
        beds: 3,
        baths: 2,
        area: 1300,
        images: [],
        description: "Lovely townhouse with park access and garage.",
    },
    {
        id: "p8",
        title: "Renovated Historic Home",
        price: 2700,
        address: "3 Heritage Way",
        beds: 4,
        baths: 3,
        area: 2000,
        images: [],
        description: "Charming historic property fully renovated.",
    },
    {
        id: "p9",
        title: "Penthouse Suite",
        price: 6100,
        address: "500 Skyline Ave",
        beds: 3,
        baths: 3,
        area: 2100,
        images: [],
        description: "Top-floor penthouse with panoramic city views.",
    },
    {
        id: "p10",
        title: "Countryside Cottage",
        price: 1400,
        address: "7 Meadow Rd",
        beds: 2,
        baths: 1,
        area: 980,
        images: [],
        description: "Cozy cottage surrounded by nature.",
    },
    {
        id: "p11",
        title: "Riverside Bungalow",
        price: 2300,
        address: "12 Riverside",
        beds: 3,
        baths: 2,
        area: 1500,
        images: [],
        description: "Peaceful bungalow with river access.",
    },
    {
        id: "p12",
        title: "Urban Designer Flat",
        price: 2000,
        address: "88 Design St",
        beds: 2,
        baths: 2,
        area: 850,
        images: [],
        description: "Stylish flat with designer finishes and balcony.",
    },
];

export function fetchProperties() {
    return MOCK_PROPERTIES;
}

export function getProperty(id) {
    return MOCK_PROPERTIES.find((p) => p.id === id);
}
